"""Initial

Revision ID: 48396925028a
Revises: 
Create Date: 2023-02-07 16:35:50.175894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48396925028a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('task_url', sa.String(length=212), nullable=True),
    sa.Column('tag', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tasks_id'), 'Tasks', ['id'], unique=False)
    op.create_index(op.f('ix_Tasks_name'), 'Tasks', ['name'], unique=False)
    op.create_index(op.f('ix_Tasks_tag'), 'Tasks', ['tag'], unique=False)
    op.create_index(op.f('ix_Tasks_task_url'), 'Tasks', ['task_url'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    op.create_table('TimeEntries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=212), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TimeEntries_description'), 'TimeEntries', ['description'], unique=False)
    op.create_index(op.f('ix_TimeEntries_id'), 'TimeEntries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TimeEntries_id'), table_name='TimeEntries')
    op.drop_index(op.f('ix_TimeEntries_description'), table_name='TimeEntries')
    op.drop_table('TimeEntries')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Tasks_task_url'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_tag'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_name'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_id'), table_name='Tasks')
    op.drop_table('Tasks')
    # ### end Alembic commands ###
